apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: tap-upbound
  annotations:
    meta.crossplane.io/maintainer: Upbound <atorgerson@upbound.io>
    meta.crossplane.io/source: github.com/garreeooke/tap-uxp
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration enables build service claims in to VMware Tanzu Application Platform
    meta.crossplane.io/readme: |
      This configuration enables build service claims in to VMware Tanzu Application Platform
spec:
  crossplane:
    version: ">=v1.11.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.31.0"
